server:
  port: 9876

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/universal_project?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    dynamic:
      primary: universal_project
      datasource:
        universal_project:
          url: jdbc:mysql://localhost:3306/universal_project
          username: root
          password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss    #指定使用Jackson进行日期序列化和反序列化的格式和时区
    time-zone: GMT+8

cors:
  addMapping: '/**'                        #允许跨域请求的路径模式
  allowedOriginPattern: '*'                #类似于 allowedOrigins，但是使用通配符模式进行匹配，可以更灵活地设置允许访问资源的源
  #allowedOrigins:                         #允许访问资源的源
  allowCredentials: true                   #是否允许发送认证信息（如 cookies、HTTP 认证信息）到服务器
  #allowedHeaders:                         #允许的请求头
  allowedMethods: '*'                      #允许的 HTTP 方法
  maxAge: 3600                             #预检请求的有效期

myConfig:
  swagger-ui-open: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

thread:
  corePoolSize: 8           #核心线程数
  maximumPoolSize: 16       #最大线程数
  keepAliveTime: 1          #非核心线程的闲置存活时间
  queueLength: 50           #队列长度
  unit: MINUTES             #存活时间单位

knife4j:
  # 开启增强配置
  enable: true
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码，所有文档密码都需要相同，要不然在网关无法正常切换到其他项目的文档
    password: universal
